package com.example.model

object CosmosData {

    val celestialBodies: List<CelestialBody> = listOf(
        // === PLANETS & SUN ===
        CelestialBody(
            id = "sun",
            name = "The Sun",
            subtitle = "G-type Main-Sequence Star (Yellow Dwarf)",
            category = CelestialCategory.PLANETS,
            overview = "The Sun is the star at the center of the Solar System. It is a nearly perfect sphere of hot plasma, heated to incandescence by nuclear fusion reactions in its core. It accounts for about 99.86% of the total mass of the entire Solar System, providing the gravitational engine and light and heat that sustains life on Earth.",
            keyFacts = listOf(
                "Contains 99.86% of all mass in the entire Solar System.",
                "Its core fuses 600 million tons of hydrogen into helium every second.",
                "Light from the Sun takes roughly 8 minutes and 20 seconds to reach Earth.",
                "Surface temperature is about 5,500°C, while its core reaches 15,000,000°C.",
                "The Sun has an 11-year solar activity cycle with flipping magnetic poles."
            ),
            diameter = "1,392,700 km (109 × Earth)",
            mass = "1.989 × 10³⁰ kg (333,000 × Earth)",
            distance = "0 km (Center of Solar System)",
            orbitalPeriod = "230 Million Years (around Milky Way core)",
            dayLength = "25 to 35 Earth Days (Differential rotation)",
            surfaceGravity = "274 m/s² (28g)",
            surfaceTemp = "5,500°C (Surface) / 15,000,000°C (Core)",
            atmosphere = "73% Hydrogen, 25% Helium, <2% Oxygen, Carbon, Neon, Iron",
            moonsCount = 8, // 8 major planets orbiting
            discoveryYear = "Ancient",
            historicalSignificance = "Worshiped by every ancient civilization as the giver of light and life. Copernicus placed it at the center of the universe in 1543.",
            nasaMissions = listOf("Parker Solar Probe", "SOHO", "Solar Dynamics Observatory (SDO)", "Stereo", "Ulysses"),
            structureLayers = listOf(
                PlanetLayer("Inner Core", "0 - 175,000 km", "Nuclear fusion zone converting H to He at 15M°C", 0xFFFFFBEB),
                PlanetLayer("Radiative Zone", "175,000 - 490,000 km", "Photons take up to 100,000 years to traverse outward", 0xFFFDE047),
                PlanetLayer("Convection Zone", "490,000 - 700,000 km", "Giant boiling plasma cells carrying heat to surface", 0xFFF97316),
                PlanetLayer("Photosphere", "Top 500 km", "Visible surface emitting sunlight", 0xFFEA580C),
                PlanetLayer("Corona", "Millions of km", "Thin ionized outer halo hotter than surface (1-3M°C)", 0xFFFBBF24)
            ),
            textureType = "sun",
            primaryColorHex = 0xFFF59E0B,
            secondaryColorHex = 0xFFDC2626,
            relativeSizeRatio = 4.5f
        ),
        CelestialBody(
            id = "mercury",
            name = "Mercury",
            subtitle = "Innermost & Smallest Terrestrial Planet",
            category = CelestialCategory.PLANETS,
            overview = "Mercury is the smallest planet in the Solar System and the closest to the Sun. Its orbit around the Sun takes only 87.97 Earth days, the shortest of all the Sun's planets. Mercury has virtually no atmosphere to trap heat, resulting in extreme temperature swings between scorching day and freezing night.",
            keyFacts = listOf(
                "Experiences the most extreme temperature swings: from 430°C by day to -180°C by night.",
                "Has a giant metallic iron core that makes up nearly 85% of the planet's radius.",
                "Despite being closest to the Sun, water ice exists inside permanently shadowed polar craters.",
                "Has no moons and no significant rings.",
                "Rotates slowly: three rotations on its axis for every two orbits around the Sun (3:2 spin-orbit resonance)."
            ),
            diameter = "4,879 km (0.38 × Earth)",
            mass = "3.301 × 10²³ kg (0.055 × Earth)",
            distance = "57.9 Million km (0.39 AU)",
            orbitalPeriod = "88 Earth Days",
            dayLength = "58.6 Earth Days",
            surfaceGravity = "3.7 m/s² (0.38g)",
            surfaceTemp = "-180°C to 430°C",
            atmosphere = "Trace exosphere: Oxygen, Sodium, Hydrogen, Helium, Potassium",
            moonsCount = 0,
            discoveryYear = "Ancient (Babylonian records ~14th century BC)",
            historicalSignificance = "Named by Romans after the swift-footed messenger god because it moves so rapidly across the sky.",
            nasaMissions = listOf("Mariner 10 (1974-1975)", "MESSENGER (2011-2015)", "BepiColombo (ESA/JAXA partner)"),
            structureLayers = listOf(
                PlanetLayer("Solid Inner Core", "0 - 1,000 km", "Solid metallic iron-nickel core", 0xFF78716C),
                PlanetLayer("Molten Outer Core", "1,000 - 2,000 km", "Liquid iron generating a weak magnetic field", 0xFF9CA3AF),
                PlanetLayer("Silicate Mantle", "2,000 - 2,400 km", "Dense silicate rock shell (~400 km thick)", 0xFF64748B),
                PlanetLayer("Rocky Crust", "2,400 - 2,440 km", "Heavily impact-cratered brittle surface", 0xFF475569)
            ),
            textureType = "mercury",
            primaryColorHex = 0xFF94A3B8,
            secondaryColorHex = 0xFF475569,
            relativeSizeRatio = 0.55f
        ),
        CelestialBody(
            id = "venus",
            name = "Venus",
            subtitle = "Earth's Toxic Twin & Hottest Planet",
            category = CelestialCategory.PLANETS,
            overview = "Venus is the second planet from the Sun. It is named after the Roman goddess of love and beauty. As the brightest natural object in Earth's night sky after the Moon, Venus can cast shadows and is often called the Morning Star or Evening Star. Its runaway greenhouse effect creates surface temperatures hotter than an oven.",
            keyFacts = listOf(
                "Hottest planet in the Solar System (surface 465°C), hotter even than Mercury.",
                "Surface atmospheric pressure is 92 times that of Earth (equivalent to 900m deep under the sea).",
                "Spins backwards (retrograde rotation) compared to most planets; Sun rises in the west.",
                "A day on Venus (243 Earth days) is longer than its entire year (225 Earth days).",
                "Clouds are composed of highly concentrated sulfuric acid droplets."
            ),
            diameter = "12,104 km (0.95 × Earth)",
            mass = "4.867 × 10²⁴ kg (0.815 × Earth)",
            distance = "108.2 Million km (0.72 AU)",
            orbitalPeriod = "224.7 Earth Days",
            dayLength = "243 Earth Days (Retrograde)",
            surfaceGravity = "8.87 m/s² (0.90g)",
            surfaceTemp = "465°C (Uniform globally)",
            atmosphere = "96.5% Carbon Dioxide, 3.5% Nitrogen, clouds of Sulfuric Acid",
            moonsCount = 0,
            discoveryYear = "Ancient",
            historicalSignificance = "Galileo observed phases of Venus in 1610, providing definitive observational proof of Copernicus's heliocentric model.",
            nasaMissions = listOf("Mariner 2 (First successful planetary flyby 1962)", "Pioneer Venus (1978)", "Magellan Radar Mapper (1989-1994)", "DAVINCI & VERITAS (Upcoming)"),
            structureLayers = listOf(
                PlanetLayer("Metallic Core", "0 - 3,000 km", "Iron-nickel core roughly 3,000 km in radius", 0xFFD97706),
                PlanetLayer("Silicate Mantle", "3,000 - 5,950 km", "Molten/plastic silicate rock undergoing active volcanism", 0xFFCA8A04),
                PlanetLayer("Basaltic Crust", "5,950 - 6,050 km", "Volcanic basalt plains and vast shield volcanoes", 0xFFEAB308),
                PlanetLayer("Superdense Atmosphere", "6,050 - 6,150 km", "Super-critical CO₂ envelope with sulfuric acid storm bands", 0xFFFEF08A)
            ),
            textureType = "venus",
            primaryColorHex = 0xFFFBBF24,
            secondaryColorHex = 0xFFD97706,
            relativeSizeRatio = 0.95f
        ),
        CelestialBody(
            id = "earth",
            name = "Earth",
            subtitle = "The Blue Marble & Cradle of Life",
            category = CelestialCategory.PLANETS,
            overview = "Earth is the third planet from the Sun and the only astronomical object known to harbor life. About 71% of Earth's surface is covered by liquid water oceans, and it possesses a protective geomagnetic field, dynamic tectonic plates, and a nitrogen-oxygen atmosphere tuned for living organisms.",
            keyFacts = listOf(
                "Only known planet with liquid water oceans on its surface and abundant biological life.",
                "Has a large natural satellite (the Moon) that stabilizes Earth's axial tilt and climate.",
                "Protected from lethal cosmic rays and solar storms by its molten iron dynamo magnetic field.",
                "Atmosphere consists of 78% Nitrogen and 21% Oxygen created largely by photosynthetic life.",
                "Earth is the densest major planet in the entire Solar System (5.51 g/cm³)."
            ),
            diameter = "12,742 km (1.0 × Earth)",
            mass = "5.972 × 10²⁴ kg (1.0 × Earth)",
            distance = "149.6 Million km (1.0 AU)",
            orbitalPeriod = "365.25 Days (1 Year)",
            dayLength = "23 Hours 56 Min (24h Solar Day)",
            surfaceGravity = "9.807 m/s² (1.0g)",
            surfaceTemp = "-88°C (Antarctica) to 58°C (Deserts), Mean 15°C",
            atmosphere = "78% Nitrogen, 21% Oxygen, 0.93% Argon, 0.04% Carbon Dioxide",
            moonsCount = 1,
            discoveryYear = "Ancient",
            historicalSignificance = "Our home planet. Apollo 8's 1968 'Earthrise' photo transformed human consciousness regarding planetary fragility.",
            nasaMissions = listOf("Apollo Program (1968-1972)", "Landsat series", "Terra & Aqua", "International Space Station", "GRACE"),
            structureLayers = listOf(
                PlanetLayer("Solid Inner Core", "0 - 1,220 km", "Solid crystalline iron-nickel alloy at ~5,400°C", 0xFFFEF3C7),
                PlanetLayer("Liquid Outer Core", "1,220 - 3,480 km", "Swirling liquid iron generating Earth's magnetic shield", 0xFFF59E0B),
                PlanetLayer("Mantle", "3,480 - 6,340 km", "Viscous silicate rock driving plate tectonics and volcanoes", 0xFFDC2626),
                PlanetLayer("Crust & Hydrosphere", "6,340 - 6,371 km", "Continental and oceanic crust bathed in liquid water", 0xFF0284C7)
            ),
            textureType = "earth",
            primaryColorHex = 0xFF38BDF8,
            secondaryColorHex = 0xFF10B981,
            relativeSizeRatio = 1.0f
        ),
        CelestialBody(
            id = "mars",
            name = "Mars",
            subtitle = "The Red Planet & Future Human Frontier",
            category = CelestialCategory.PLANETS,
            overview = "Mars is the fourth planet from the Sun and the second-smallest planet in the Solar System. Its reddish appearance is caused by iron oxide (rust) pervasive on its surface. Mars hosts Olympus Mons, the largest volcano in the Solar System, and Valles Marineris, a canyon system that dwarfs Earth's Grand Canyon.",
            keyFacts = listOf(
                "Home to Olympus Mons, an extinct shield volcano 22 km high (nearly 3 times Mount Everest).",
                "Hosts Valles Marineris, a vast canyon system over 4,000 km long and up to 7 km deep.",
                "Abundant evidence shows liquid water rivers and lakes flowed across ancient Martian soil 3.8 billion years ago.",
                "Has two small irregularly shaped potato-like moons: Phobos and Deimos.",
                "NASA rovers currently search for signs of past microbial life in ancient Jezero Crater lakebed."
            ),
            diameter = "6,779 km (0.53 × Earth)",
            mass = "6.417 × 10²³ kg (0.107 × Earth)",
            distance = "227.9 Million km (1.52 AU)",
            orbitalPeriod = "687 Earth Days (1.88 Years)",
            dayLength = "24 Hours 37 Min (1 Sol)",
            surfaceGravity = "3.72 m/s² (0.38g)",
            surfaceTemp = "-140°C to 20°C (Average -63°C)",
            atmosphere = "95.3% Carbon Dioxide, 2.6% Nitrogen, 1.9% Argon, trace water vapor",
            moonsCount = 2,
            discoveryYear = "Ancient",
            historicalSignificance = "Long inspired science fiction and scientific quests for extraterrestrial life, from Schiaparelli's 'canals' to modern rover discoveries.",
            nasaMissions = listOf("Viking 1 & 2 (1976)", "Pathfinder & Sojourner (1997)", "Spirit & Opportunity (2004)", "Curiosity (2012-Present)", "Perseverance & Ingenuity (2021-Present)"),
            structureLayers = listOf(
                PlanetLayer("Dense Metallic Core", "0 - 1,800 km", "Partially molten iron, nickel, and sulfur core", 0xFF991B1B),
                PlanetLayer("Silicate Mantle", "1,800 - 3,340 km", "Rock mantle cooler and less dynamic than Earth's", 0xFFC2410C),
                PlanetLayer("Basaltic Rust Crust", "3,340 - 3,390 km", "Iron oxide-rich crust layered with dust and volcanic plains", 0xFFEA580C)
            ),
            textureType = "mars",
            primaryColorHex = 0xFFEF4444,
            secondaryColorHex = 0xFFB45309,
            relativeSizeRatio = 0.65f
        ),
        CelestialBody(
            id = "jupiter",
            name = "Jupiter",
            subtitle = "King of the Planets & Gas Giant Colossus",
            category = CelestialCategory.PLANETS,
            overview = "Jupiter is the fifth planet from the Sun and the largest in the Solar System. It is a gas giant with a mass more than two and a half times that of all the other planets in the Solar System combined. Its Great Red Spot is a colossal anticyclonic storm larger than Earth that has raged for centuries.",
            keyFacts = listOf(
                "Mass is 318 times that of Earth and more than double all other planets combined.",
                "The Great Red Spot is a monster storm that has raged for at least 350 years.",
                "Rotates faster than any other planet: a Jovian day is just 9 hours and 55 minutes.",
                "Has at least 95 confirmed moons, including Ganymede (larger than Mercury) and Europa (ocean world).",
                "Its massive magnetic field is up to 20,000 times stronger than Earth's."
            ),
            diameter = "139,820 km (11.0 × Earth)",
            mass = "1.898 × 10²⁷ kg (317.8 × Earth)",
            distance = "778.5 Million km (5.2 AU)",
            orbitalPeriod = "11.86 Earth Years",
            dayLength = "9 Hours 55 Min",
            surfaceGravity = "24.79 m/s² (2.53g)",
            surfaceTemp = "-110°C (Cloud tops) / 24,000°C (Core boundary)",
            atmosphere = "90% Hydrogen, 10% Helium, traces of Methane, Ammonia, Water vapor",
            moonsCount = 95,
            discoveryYear = "Ancient",
            historicalSignificance = "Galileo discovered Jupiter's 4 major moons in 1610, the first definitive proof that celestial bodies orbit objects other than Earth.",
            nasaMissions = listOf("Pioneer 10 & 11 (1973-74)", "Voyager 1 & 2 (1979)", "Galileo Orbiter (1995-2003)", "Juno Orbiter (2016-Present)", "Europa Clipper (En Route)"),
            structureLayers = listOf(
                PlanetLayer("Dense Heavy Core", "0 - 10,000 km", "Superheated rock, ice, and metallic elements", 0xFF475569),
                PlanetLayer("Liquid Metallic Hydrogen", "10,000 - 55,000 km", "Hydrogen compressed into an electrical conductor fluid", 0xFFD97706),
                PlanetLayer("Molecular Liquid Hydrogen", "55,000 - 69,000 km", "Fluid ocean transitioning gradually to atmospheric gas", 0xFFF59E0B),
                PlanetLayer("Turbulent Cloud Belts", "Top 1,000 km", "Ammonia, ammonium hydrosulfide and water clouds", 0xFFFED7AA)
            ),
            textureType = "jupiter",
            primaryColorHex = 0xFFF59E0B,
            secondaryColorHex = 0xFFD97706,
            relativeSizeRatio = 2.4f
        ),
        CelestialBody(
            id = "saturn",
            name = "Saturn",
            subtitle = "The Jewel of the Solar System",
            category = CelestialCategory.PLANETS,
            overview = "Saturn is the sixth planet from the Sun and the second-largest in the Solar System. It is famous for its majestic planetary ring system composed of billions of chunks of ice and rock. Saturn is the only planet in the Solar System whose average density is less than liquid water.",
            keyFacts = listOf(
                "Spectacular ring system spans up to 282,000 km across but is only about 10 meters to 1 km thick.",
                "Lowest density of any planet (0.687 g/cm³); Saturn would float if placed in a giant bathtub of water.",
                "Has 146 confirmed moons, the most of any planet, led by Titan (with a dense nitrogen atmosphere and methane lakes).",
                "Features a bizarre, persistent hexagonal jet stream storm at its north pole.",
                "Cassini spacecraft orbited Saturn for 13 years before diving into its atmosphere in 2017."
            ),
            diameter = "116,460 km (9.1 × Earth)",
            mass = "5.683 × 10²⁶ kg (95.2 × Earth)",
            distance = "1.434 Billion km (9.58 AU)",
            orbitalPeriod = "29.45 Earth Years",
            dayLength = "10 Hours 33 Min",
            surfaceGravity = "10.44 m/s² (1.06g)",
            surfaceTemp = "-140°C (Cloud tops)",
            atmosphere = "96% Hydrogen, 3% Helium, 0.4% Methane, Ammonia",
            moonsCount = 146,
            discoveryYear = "Ancient",
            historicalSignificance = "Christiaan Huygens first recognized Saturn's rings in 1655 using a telescope, and discovered its largest moon, Titan.",
            nasaMissions = listOf("Pioneer 11 (1979)", "Voyager 1 & 2 (1980-81)", "Cassini-Huygens (2004-2017)", "Dragonfly (Upcoming to Titan)"),
            structureLayers = listOf(
                PlanetLayer("Rocky/Icy Core", "0 - 12,000 km", "Dense core of iron-nickel, rock, and high-pressure ice", 0xFF64748B),
                PlanetLayer("Metallic Hydrogen Layer", "12,000 - 30,000 km", "Liquid metallic hydrogen generating magnetic field", 0xFFCA8A04),
                PlanetLayer("Molecular Hydrogen Ocean", "30,000 - 57,000 km", "Fluid hydrogen and helium with helium rain droplets", 0xFFEAB308),
                PlanetLayer("Atmospheric Cloud Deck", "Top 1,000 km", "Golden ammonia ice haze and wind jets exceeding 1,800 km/h", 0xFFFEF08A)
            ),
            textureType = "saturn",
            primaryColorHex = 0xFFFBBF24,
            secondaryColorHex = 0xFFCA8A04,
            hasRings = true,
            ringColorHex = 0xFFFDE68A,
            ringInnerRatio = 1.35f,
            ringOuterRatio = 2.3f,
            relativeSizeRatio = 2.1f
        ),
        CelestialBody(
            id = "uranus",
            name = "Uranus",
            subtitle = "The Sideways Ice Giant",
            category = CelestialCategory.PLANETS,
            overview = "Uranus is the seventh planet from the Sun. It has the third-largest planetary radius and fourth-largest planetary mass in the Solar System. Uranus is unique because it rotates completely on its side with an axial tilt of 97.8 degrees, likely the result of a cataclysmic collision with an Earth-sized protoplanet billions of years ago.",
            keyFacts = listOf(
                "Rolls on its side with an axial tilt of 97.8°, causing 42-year long seasons of continuous sunlight or darkness.",
                "Has the coldest planetary atmosphere in the Solar System, dropping to -224°C.",
                "Classified as an Ice Giant: its interior is dominated by dense 'ices' of water, methane, and ammonia.",
                "Atmospheric methane absorbs red light, giving Uranus its soft aquamarine cyan color.",
                "Has 13 known narrow dark rings and 28 moons named after characters from Shakespeare and Alexander Pope."
            ),
            diameter = "50,724 km (4.0 × Earth)",
            mass = "8.681 × 10²⁵ kg (14.5 × Earth)",
            distance = "2.871 Billion km (19.2 AU)",
            orbitalPeriod = "84.0 Earth Years",
            dayLength = "17 Hours 14 Min (Retrograde & Tilted)",
            surfaceGravity = "8.69 m/s² (0.89g)",
            surfaceTemp = "-195°C (Average) to -224°C (Minimum)",
            atmosphere = "83% Hydrogen, 15% Helium, 2.3% Methane",
            moonsCount = 28,
            discoveryYear = "1781 by William Herschel",
            historicalSignificance = "First planet discovered in modern history using a telescope, doubling the known radius of the Solar System.",
            nasaMissions = listOf("Voyager 2 (Only spacecraft flyby, January 1986)", "Hubble Space Telescope observations"),
            structureLayers = listOf(
                PlanetLayer("Rocky Silicate Core", "0 - 5,000 km", "Silicate rock and iron-nickel mixture", 0xFF475569),
                PlanetLayer("Supercritical Icy Mantle", "5,000 - 20,000 km", "Slushy high-pressure ocean of water, ammonia, and methane", 0xFF0284C7),
                PlanetLayer("Hydrogen-Helium Atmosphere", "20,000 - 25,300 km", "Pale cyan methane haze cloud layer", 0xFF38BDF8)
            ),
            textureType = "uranus",
            primaryColorHex = 0xFF38BDF8,
            secondaryColorHex = 0xFF0284C7,
            hasRings = true,
            ringColorHex = 0xFF7DD3FC,
            ringInnerRatio = 1.25f,
            ringOuterRatio = 1.7f,
            relativeSizeRatio = 1.4f
        ),
        CelestialBody(
            id = "neptune",
            name = "Neptune",
            subtitle = "The Supersonic Azure Wind Giant",
            category = CelestialCategory.PLANETS,
            overview = "Neptune is the eighth and outermost known major planet from the Sun. It is 17 times the mass of Earth and slightly more massive than its twin Uranus. Neptune is famous for having the fastest planetary winds in the Solar System, gusting up to 2,100 km/h, and a vivid deep azure blue atmosphere.",
            keyFacts = listOf(
                "Features the fastest winds recorded in the Solar System, exceeding 2,100 km/h (supersonic).",
                "First planet predicted mathematically by Urbain Le Verrier before it was ever seen through a telescope in 1846.",
                "Takes nearly 165 Earth years to complete a single orbit around the Sun.",
                "Has a giant retrograde moon, Triton, with active cryovolcanoes spewing liquid nitrogen geysers.",
                "Emits 2.6 times more heat energy than it receives from the distant Sun."
            ),
            diameter = "49,244 km (3.9 × Earth)",
            mass = "1.024 × 10²⁶ kg (17.1 × Earth)",
            distance = "4.495 Billion km (30.1 AU)",
            orbitalPeriod = "164.8 Earth Years",
            dayLength = "16 Hours 6 Min",
            surfaceGravity = "11.15 m/s² (1.14g)",
            surfaceTemp = "-201°C (Average)",
            atmosphere = "80% Hydrogen, 19% Helium, 1.5% Methane",
            moonsCount = 16,
            discoveryYear = "1846 by Johann Galle & Urbain Le Verrier",
            historicalSignificance = "A triumph of Newton's law of gravitation: discovered via gravitational perturbations on Uranus's orbit.",
            nasaMissions = listOf("Voyager 2 (Only spacecraft encounter, August 1989)", "Hubble & James Webb (JWST ring imaging)"),
            structureLayers = listOf(
                PlanetLayer("Rocky Iron Core", "0 - 7,000 km", "Iron, nickel, and silicate rock roughly 1.2 Earth masses", 0xFF334155),
                PlanetLayer("Hot Dense Icy Mantle", "7,000 - 20,000 km", "Highly conductive water-ammonia-methane ionic fluid", 0xFF1D4ED8),
                PlanetLayer("Deep Azure Atmosphere", "20,000 - 24,600 km", "Vivid blue atmosphere with high-altitude methane cirrus clouds", 0xFF2563EB)
            ),
            textureType = "neptune",
            primaryColorHex = 0xFF2563EB,
            secondaryColorHex = 0xFF1E40AF,
            hasRings = true,
            ringColorHex = 0xFF60A5FA,
            ringInnerRatio = 1.2f,
            ringOuterRatio = 1.5f,
            relativeSizeRatio = 1.35f
        ),
        CelestialBody(
            id = "pluto",
            name = "Pluto",
            subtitle = "King of the Kuiper Belt & Dwarf Planet",
            category = CelestialCategory.PLANETS,
            overview = "Pluto is a dwarf planet in the Kuiper Belt, a ring of icy bodies beyond the orbit of Neptune. Discovered in 1930, it was classified as the ninth planet for 76 years until the IAU redefined the term in 2006. In 2015, NASA's New Horizons probe revealed a geologically active world of nitrogen ice glaciers, towering water-ice mountains, and a heart-shaped plain named Tombaugh Regio.",
            keyFacts = listOf(
                "Features Tombaugh Regio, a gigantic heart-shaped glacier of frozen nitrogen and carbon monoxide.",
                "Has five known moons; Charon is so large that the two orbit a common center of gravity outside Pluto's surface.",
                "Has a thin blue atmospheric haze made of complex organic molecules called tholins.",
                "Discovered in 1930 by Clyde Tombaugh at Lowell Observatory in Arizona.",
                "Surface contains water-ice mountains as tall as the Rocky Mountains, kept rigid by extreme cold."
            ),
            diameter = "2,376 km (0.18 × Earth)",
            mass = "1.303 × 10²² kg (0.0022 × Earth)",
            distance = "5.906 Billion km (39.5 AU)",
            orbitalPeriod = "248.0 Earth Years",
            dayLength = "6.39 Earth Days (153.3 Hours)",
            surfaceGravity = "0.62 m/s² (0.063g)",
            surfaceTemp = "-230°C to -223°C",
            atmosphere = "Nitrogen, Methane, Carbon Monoxide (Tenacious seasonal exosphere)",
            moonsCount = 5,
            discoveryYear = "1930 by Clyde Tombaugh",
            historicalSignificance = "Reclassified to Dwarf Planet in 2006, opening our understanding of the vast Kuiper Belt of icy worlds.",
            nasaMissions = listOf("New Horizons (Historic close flyby on July 14, 2015)"),
            structureLayers = listOf(
                PlanetLayer("Dense Silicate Core", "0 - 850 km", "Rock and hydrated minerals comprising 70% of mass", 0xFF78716C),
                PlanetLayer("Subsurface Ocean / Ice Mantle", "850 - 1,150 km", "Possible liquid water layer under thick water-ice shell", 0xFF93C5FD),
                PlanetLayer("Nitrogen Ice Crust", "1,150 - 1,188 km", "Glacial plains of nitrogen, methane, and CO ice with tholin stains", 0xFFFDE047)
            ),
            textureType = "pluto",
            primaryColorHex = 0xFFD97706,
            secondaryColorHex = 0xFF78716C,
            relativeSizeRatio = 0.45f
        ),

        // === MAJOR MOONS ===
        CelestialBody(
            id = "moon",
            name = "The Moon (Luna)",
            subtitle = "Earth's Only Natural Satellite",
            category = CelestialCategory.MOONS,
            overview = "The Moon is Earth's only natural satellite. Formed roughly 4.5 billion years ago when a Mars-sized protoplanet named Theia collided with the early Earth, the Moon is in synchronous rotation with Earth, always showing us the same face. It is the only extraterrestrial body humans have walked upon.",
            keyFacts = listOf(
                "Only celestial body beyond Earth where humans have landed (12 NASA Apollo astronauts 1969-1972).",
                "Tidally locked to Earth, meaning its orbital period exactly matches its rotational period.",
                "Drives Earth's ocean tides and stabilizes Earth's climate and spin axis.",
                "Dark smooth plains are called 'Maria' (ancient basaltic volcanic flood lava).",
                "NASA's Artemis program will return astronauts, including the first woman and person of color, to the lunar South Pole."
            ),
            diameter = "3,474 km (0.27 × Earth)",
            mass = "7.342 × 10²² kg (0.0123 × Earth)",
            distance = "384,400 km from Earth",
            orbitalPeriod = "27.3 Earth Days",
            dayLength = "29.5 Earth Days (Lunar day/night cycle)",
            surfaceGravity = "1.62 m/s² (0.166g / 1/6th Earth)",
            surfaceTemp = "-130°C (Night) to 120°C (Day)",
            atmosphere = "Extremely tenuous exosphere: Helium, Neon, Hydrogen",
            moonsCount = 0,
            discoveryYear = "Ancient",
            historicalSignificance = "Apollo 11 landed on July 20, 1969. Neil Armstrong took 'one small step for man, one giant leap for mankind.'",
            nasaMissions = listOf("Apollo 11, 12, 14, 15, 16, 17", "Lunar Reconnaissance Orbiter (LRO)", "GRAIL", "LCROSS", "Artemis I, II, III"),
            structureLayers = listOf(
                PlanetLayer("Small Metallic Core", "0 - 350 km", "Partially molten iron core (~2% of lunar mass)", 0xFF64748B),
                PlanetLayer("Rigid Mantle", "350 - 1,670 km", "Dense olivine and pyroxene mineral mantle", 0xFF94A3B8),
                PlanetLayer("Anorthositic Crust", "1,670 - 1,737 km", "Thick regolith crust pulverized by eons of meteorite impacts", 0xFFCBD5E1)
            ),
            textureType = "moon",
            primaryColorHex = 0xFFCBD5E1,
            secondaryColorHex = 0xFF64748B,
            relativeSizeRatio = 0.5f
        ),
        CelestialBody(
            id = "europa",
            name = "Europa",
            subtitle = "Jupiter's Ocean Moon & Prime Astrobiology Target",
            category = CelestialCategory.MOONS,
            overview = "Europa is the smallest of the four Galilean moons orbiting Jupiter. Beneath its smooth, crisscrossed ice crust lies a global liquid water ocean containing more water than all of Earth's oceans combined. Warmed by tidal gravitational flexing from Jupiter, Europa is considered one of the most promising locations in the Solar System to find extraterrestrial microbial life.",
            keyFacts = listOf(
                "Subsurface liquid ocean contains more than twice the volume of all Earth's oceans combined.",
                "Smooth surface is crisscrossed by dark reddish fractures called 'lineae' caused by tidal stresses.",
                "Water vapor geysers have been detected erupting dozens of kilometers into space.",
                "NASA's Europa Clipper mission launched in October 2024 to determine if Europa has habitable conditions."
            ),
            diameter = "3,121 km (0.245 × Earth)",
            mass = "4.800 × 10²² kg",
            distance = "670,900 km from Jupiter",
            orbitalPeriod = "3.55 Earth Days",
            dayLength = "3.55 Earth Days (Tidally locked)",
            surfaceGravity = "1.315 m/s² (0.134g)",
            surfaceTemp = "-160°C to -220°C",
            atmosphere = "Tenuous Oxygen exosphere produced by radiolysis of surface ice",
            moonsCount = 0,
            discoveryYear = "1610 by Galileo Galilei",
            historicalSignificance = "Turned astrobiology upside down: revealed that habitability can exist far outside the traditional circumstellar goldilocks zone via tidal heating.",
            nasaMissions = listOf("Voyager 1 & 2", "Galileo Orbiter (1995-2003)", "Europa Clipper (Launched 2024, arriving 2030)"),
            structureLayers = listOf(
                PlanetLayer("Metallic Core", "0 - 600 km", "Iron-nickel metallic center", 0xFF64748B),
                PlanetLayer("Silicate Mantle", "600 - 1,450 km", "Rocky mantle in direct contact with ocean bottom", 0xFF94A3B8),
                PlanetLayer("Global Liquid Ocean", "1,450 - 1,540 km", "Warm salty liquid ocean 60 to 150 km deep", 0xFF0284C7),
                PlanetLayer("Water-Ice Shell", "1,540 - 1,560 km", "Cracked ice crust 15 to 25 km thick", 0xFFE0F2FE)
            ),
            textureType = "europa",
            primaryColorHex = 0xFFBAE6FD,
            secondaryColorHex = 0xFF9A3412,
            relativeSizeRatio = 0.48f
        ),
        CelestialBody(
            id = "titan",
            name = "Titan",
            subtitle = "Saturn's Giant Moon with Methane Lakes & Atmosphere",
            category = CelestialCategory.MOONS,
            overview = "Titan is the largest moon of Saturn and the second-largest natural satellite in the Solar System. It is larger than the planet Mercury. Titan is the only moon known to have a dense, substantial atmosphere, and the only known world besides Earth with stable bodies of surface liquid—composed of liquid methane and ethane rivers, lakes, and seas.",
            keyFacts = listOf(
                "Only moon in the Solar System with a dense nitrogen atmosphere (surface pressure 1.5x Earth).",
                "Has complete hydrological cycle of methane clouds, methane rain, rivers, and liquid hydrocarbon seas (e.g. Kraken Mare).",
                "NASA is developing the Dragonfly rotorcraft lander to fly across Titan's organic sands in 2034.",
                "Surface temperature is -179°C, where water ice behaves as hard as granite rock."
            ),
            diameter = "5,149 km (0.40 × Earth, larger than Mercury)",
            mass = "1.345 × 10²³ kg (1.8 × Moon)",
            distance = "1.22 Million km from Saturn",
            orbitalPeriod = "15.95 Earth Days",
            dayLength = "15.95 Earth Days (Tidally locked)",
            surfaceGravity = "1.352 m/s² (0.138g)",
            surfaceTemp = "-179°C",
            atmosphere = "95% Nitrogen, 5% Methane, rich in complex pre-biotic tholins",
            moonsCount = 0,
            discoveryYear = "1655 by Christiaan Huygens",
            historicalSignificance = "ESA's Huygens probe landed on Titan on January 14, 2005—the most distant robotic landing in human history.",
            nasaMissions = listOf("Voyager 1", "Cassini-Huygens (Huygens lander 2005)", "Dragonfly (NASA New Frontiers Mission)"),
            structureLayers = listOf(
                PlanetLayer("Rocky Silicate Core", "0 - 2,000 km", "Dense core of silicate rock and iron", 0xFF78716C),
                PlanetLayer("High-Pressure Ice / Subsurface Ocean", "2,000 - 2,450 km", "Liquid water-ammonia ocean capped by ice", 0xFF0284C7),
                PlanetLayer("Rigid Ice Crust & Dunes", "2,450 - 2,574 km", "Water-ice crust with methane dunes and hydrocarbon seas", 0xFFFBBF24)
            ),
            textureType = "titan",
            primaryColorHex = 0xFFF59E0B,
            secondaryColorHex = 0xFF78350F,
            relativeSizeRatio = 0.6f
        ),

        // === GALAXIES & DEEP SPACE ===
        CelestialBody(
            id = "milky_way",
            name = "The Milky Way",
            subtitle = "Our Home Barred Spiral Galaxy",
            category = CelestialCategory.GALAXIES,
            overview = "The Milky Way is the galaxy that contains our Solar System. A barred spiral galaxy with a diameter estimated at 100,000 to 120,000 light-years, it contains between 100 and 400 billion stars and at least that many planets. At its very center lies Sagittarius A*, a supermassive black hole with a mass of 4.1 million Suns.",
            keyFacts = listOf(
                "Contains an estimated 100 to 400 billion stars and hundreds of billions of planets.",
                "Spans approximately 100,000 light-years across and about 1,000 light-years thick at the disk.",
                "Our Solar System is located in the Orion-Cygnus Arm, about 26,000 light-years from the galactic center.",
                "Travels through intergalactic space toward a collision with the Andromeda galaxy in about 4.5 billion years.",
                "Rotates as a cosmic pinwheel; our Sun takes 230 million years to complete one 'Galactic Year'."
            ),
            diameter = "100,000 - 120,000 Light Years",
            mass = "1.5 × 10¹² Solar Masses (including Dark Matter halo)",
            distance = "We are inside it (~26,000 ly from core)",
            orbitalPeriod = "230 Million Years (Sun's orbit)",
            dayLength = "N/A",
            surfaceGravity = "Varies across spiral arms",
            surfaceTemp = "From 2.7K (Cosmic background) to millions of degrees in stellar cores",
            atmosphere = "Interstellar medium: 90% Hydrogen, 10% Helium gas and dust grains",
            moonsCount = 59, // Satellite dwarf galaxies (Magellanic clouds, Sagittarius dwarf, etc.)
            discoveryYear = "Ancient (First resolved into individual stars by Galileo in 1610)",
            historicalSignificance = "In the 1920s, Edwin Hubble discovered that the Milky Way is not the entire universe, but just one of hundreds of billions of galaxies.",
            nasaMissions = listOf("Hubble Space Telescope", "James Webb Space Telescope (JWST)", "Spitzer Space Telescope", "Gaia (ESA/NASA)"),
            structureLayers = listOf(
                PlanetLayer("Sagittarius A* Core", "Center", "Supermassive black hole (4.1M solar masses)", 0xFF000000),
                PlanetLayer("Galactic Bulge & Bar", "0 - 10,000 ly", "Dense spherical swarm of ancient red and yellow stars", 0xFFFEF08A),
                PlanetLayer("Spiral Disk & Arms", "10,000 - 50,000 ly", "Thin disk with star-forming nebulae, open clusters, and young blue stars", 0xFF38BDF8),
                PlanetLayer("Dark Matter Halo", "Out to 300,000 ly", "Invisible sphere of dark matter comprising 90% of galaxy's mass", 0xFF6B21A8)
            ),
            textureType = "galaxy",
            primaryColorHex = 0xFFA855F7,
            secondaryColorHex = 0xFF38BDF8,
            relativeSizeRatio = 3.5f
        ),
        CelestialBody(
            id = "andromeda",
            name = "Andromeda Galaxy (M31)",
            subtitle = "Majestic Neighbor & Spiral Sister",
            category = CelestialCategory.GALAXIES,
            overview = "The Andromeda Galaxy is a barred spiral galaxy approximately 2.5 million light-years from Earth and the nearest major galaxy to the Milky Way. Spanning roughly 220,000 light-years across, it contains roughly one trillion stars. It is on a direct collision course with the Milky Way, destined to merge into a giant elliptical galaxy dubbed 'Milkomeda' in 4.5 billion years.",
            keyFacts = listOf(
                "Contains approximately 1 trillion stars, more than double the count of the Milky Way.",
                "Approaching the Milky Way at 110 kilometers per second (400,000 km/h).",
                "Most distant object visible to the naked human eye under dark skies.",
                "Hosts a double nucleus and a supermassive black hole of 100-230 million solar masses."
            ),
            diameter = "220,000 Light Years",
            mass = "1.5 - 2.0 × 10¹² Solar Masses",
            distance = "2.537 Million Light Years",
            orbitalPeriod = "N/A (Local Group member)",
            dayLength = "N/A",
            surfaceGravity = "Galactic scale gravitational well",
            surfaceTemp = "Intergalactic void: 2.725 Kelvin",
            atmosphere = "Interstellar gas and dust, dense molecular clouds",
            moonsCount = 14, // Major satellite galaxies (M32, M110)
            discoveryYear = "964 AD by Persian astronomer Abd al-Rahman al-Sufi",
            historicalSignificance = "Edwin Hubble's 1923 discovery of a Cepheid variable star in M31 proved definitively that 'spiral nebulae' are entire island universes.",
            nasaMissions = listOf("Hubble Space Telescope (PHAT Survey of 100M stars)", "Swift Gamma-Ray Explorer", "Chandra X-Ray Observatory"),
            structureLayers = listOf(
                PlanetLayer("Supermassive Black Hole", "Core", "Central singularity with mass of 140M Suns", 0xFF000000),
                PlanetLayer("Central Bulge", "0 - 15,000 ly", "Dense population of older population II stars", 0xFFFDE047),
                PlanetLayer("Spiral Disk & Dust Rings", "15,000 - 110,000 ly", "Vast spiral arms with intense blue stellar nurseries", 0xFF818CF8)
            ),
            textureType = "andromeda",
            primaryColorHex = 0xFF818CF8,
            secondaryColorHex = 0xFFC084FC,
            relativeSizeRatio = 3.8f
        ),
        CelestialBody(
            id = "black_hole_sgr_a",
            name = "Sagittarius A* (Black Hole)",
            subtitle = "The Gravitational Monster at Milky Way's Core",
            category = CelestialCategory.GALAXIES,
            overview = "Sagittarius A* is a supermassive black hole located at the dynamical center of the Milky Way galaxy. With a mass equivalent to 4.15 million Suns packed inside a region smaller than the orbit of Mercury, its gravitational field bends space and time so intensely that nothing, not even light, can escape past its event horizon.",
            keyFacts = listOf(
                "Mass is equal to 4.15 million times the mass of our Sun.",
                "Event horizon diameter is about 24 million kilometers (17 times the Sun's diameter).",
                "Stars near Sgr A* (like star S2) orbit at velocities exceeding 7,000 km/s (nearly 3% speed of light).",
                "Directly imaged by the Event Horizon Telescope (EHT) collaboration and revealed to humanity in May 2022.",
                "Reinhard Genzel and Andrea Ghez won the 2020 Nobel Prize in Physics for tracking stars orbiting Sgr A*."
            ),
            diameter = "24 Million km (Event Horizon / Schwarzschild radius ~12M km)",
            mass = "4.154 × 10⁶ Solar Masses (8.26 × 10³⁶ kg)",
            distance = "26,673 Light Years from Earth",
            orbitalPeriod = "Spin parameter ~0.9 (Near maximum relativistic spin)",
            dayLength = "Innermost stable circular orbit: Minutes",
            surfaceGravity = "Infinite at singularity / extreme at horizon",
            surfaceTemp = "Hawking radiation: ~10⁻¹⁴ Kelvin / Accretion disk: Millions of °C",
            atmosphere = "Accretion flow of relativistic ionized plasma",
            moonsCount = 0, // Tens of orbiting stars (S-stars)
            discoveryYear = "1974 by Bruce Balick and Robert Brown",
            historicalSignificance = "Direct visual confirmation of Einstein's General Relativity in the strongest gravitational regime imaginable.",
            nasaMissions = listOf("Event Horizon Telescope (EHT)", "Chandra X-Ray Observatory", "NuSTAR", "James Webb Space Telescope (JWST)"),
            structureLayers = listOf(
                PlanetLayer("Gravitational Singularity", "Center (r = 0)", "Infinitely dense point where space-time curves to infinity", 0xFF000000),
                PlanetLayer("Event Horizon", "r = 12.7M km", "Boundary of no return; escape velocity equals speed of light c", 0xFF0B0D17),
                PlanetLayer("Photon Sphere", "r = 19M km", "Region where photons are forced into unstable circular orbits", 0xFFF97316),
                PlanetLayer("Accretion Disk & Lensing", "Millions of km", "Superheated plasma glowing in X-rays, gravitationally magnified", 0xFFFBBF24)
            ),
            textureType = "black_hole",
            primaryColorHex = 0xFFF97316,
            secondaryColorHex = 0xFF0B0D17,
            relativeSizeRatio = 2.0f
        ),
        CelestialBody(
            id = "pillars_of_creation",
            name = "Pillars of Creation (Eagle Nebula)",
            subtitle = "Stellar Hatchery of Gas & Cosmic Dust",
            category = CelestialCategory.GALAXIES,
            overview = "The Pillars of Creation are majestic elephant trunks of interstellar gas and dust in the Eagle Nebula (M16), roughly 6,500 light-years from Earth. Inside these monumental towers—spanning 4 to 5 light-years in height—new stars and proto-planetary disks are constantly condensing and igniting.",
            keyFacts = listOf(
                "The tallest pillar is approximately 4 light-years (38 trillion kilometers) high.",
                "Composed of cold molecular hydrogen gas and microscopic dust particles.",
                "Captured in iconic 1995 Hubble imagery and breathtaking 2022 James Webb infrared views showing glowing newborn protostars.",
                "Slowly being eroded by ultraviolet radiation and stellar winds from nearby massive newborn stars."
            ),
            diameter = "4 - 5 Light Years (Height of main pillar)",
            mass = "Estimated 200 Solar Masses of gas and dust",
            distance = "6,500 - 7,000 Light Years (Constellation Serpens)",
            orbitalPeriod = "N/A (Interstellar cloud)",
            dayLength = "N/A",
            surfaceGravity = "Local gravitational condensation",
            surfaceTemp = "-250°C to -230°C in cold gas clouds / 10,000°C at ionized edges",
            atmosphere = "Molecular Hydrogen (H₂), Polycyclic Aromatic Hydrocarbons, Carbon Monoxide",
            moonsCount = 0,
            discoveryYear = "1745 (Eagle Nebula by Jean-Philippe de Chéseaux); Imaged in 1995 by Hubble",
            historicalSignificance = "One of the most famous and influential astronomical photographs in human history, showing the birth of stars.",
            nasaMissions = listOf("Hubble Space Telescope (1995 & 2014 HD revisit)", "James Webb Space Telescope (NIRCam & MIRI 2022)", "Spitzer"),
            structureLayers = listOf(
                PlanetLayer("Cold Molecular Dust Cores", "Inner Pillars", "Dense knots where gravitational collapse spawns protostars", 0xFFB45309),
                PlanetLayer("Evaporating Gaseous Globules (EGGs)", "Pillar Fingertips", "Finger-like protrusions shielding young emerging stars", 0xFFF59E0B),
                PlanetLayer("Ionized Photo-evaporation Sheath", "Outer Boundary", "Glowing hydrogen plasma stripped by nearby O/B star radiation", 0xFF67E8F9)
            ),
            textureType = "nebula",
            primaryColorHex = 0xFFF59E0B,
            secondaryColorHex = 0xFF06B6D4,
            relativeSizeRatio = 2.5f
        ),

        // === SOLAR SYSTEMS & EXOPLANETS ===
        CelestialBody(
            id = "trappist_1",
            name = "TRAPPIST-1 System",
            subtitle = "Seven Earth-Sized Worlds Around an Ultra-Cool Dwarf",
            category = CelestialCategory.EXOPLANETS,
            overview = "TRAPPIST-1 is a red dwarf star located 39.5 light-years from Earth. It hosts the most remarkable planetary system yet discovered: seven rocky, Earth-sized planets orbiting within a compact zone. Three of these worlds (e, f, and g) reside inside the circumstellar habitable zone where liquid water could exist.",
            keyFacts = listOf(
                "Contains 7 rocky, Earth-sized planets packed tightly around an ultra-cool red dwarf star.",
                "The entire system is so compact that all seven planets orbit closer to their star than Mercury is to our Sun.",
                "Three planets (e, f, and g) orbit in the star's habitable 'Goldilocks' zone.",
                "Planets are in orbital resonances (e.g. 8:5, 5:3, 3:2), producing gravitational musical harmonies.",
                "Prime target for the James Webb Space Telescope to detect atmospheric carbon dioxide and water vapor."
            ),
            diameter = "Star: 169,000 km (0.12 × Sun) / Planets: 0.77 to 1.13 × Earth",
            mass = "Star: 0.089 Solar Masses (Near hydrogen fusion limit)",
            distance = "39.46 Light Years (Constellation Aquarius)",
            orbitalPeriod = "Planet b: 1.5 days to Planet h: 18.8 days",
            dayLength = "All planets tidally locked to their parent star",
            surfaceGravity = "0.7g to 1.0g across the seven planets",
            surfaceTemp = "From 120°C (Planet b) to -100°C (Planet h); Planet e ~15°C",
            atmosphere = "Subject of active JWST spectroscopic characterization",
            moonsCount = 0,
            discoveryYear = "2015-2017 by Michaël Gillon and NASA Spitzer Space Telescope",
            historicalSignificance = "Greatest number of Earth-sized, potentially habitable planets ever found in a single planetary system.",
            nasaMissions = listOf("Spitzer Space Telescope (500-hour observing marathon)", "James Webb Space Telescope (JWST Transits)", "Kepler (K2 Mission)"),
            structureLayers = listOf(
                PlanetLayer("Ultra-Cool Red Dwarf Star", "Center", "Long-lived M-dwarf star burning fuel for 12 trillion years", 0xFFDC2626),
                PlanetLayer("Inner Terrestrial Worlds (b, c, d)", "0.011 - 0.022 AU", "Scorched rocky worlds with thin or stripped atmospheres", 0xFFEA580C),
                PlanetLayer("Habitable Zone Worlds (e, f, g)", "0.028 - 0.046 AU", "Temperate Earth-scale rocky worlds with possible oceans", 0xFF0284C7),
                PlanetLayer("Outer Ice World (h)", "0.06 AU", "Cold frozen world at the outer edge of the system", 0xFF93C5FD)
            ),
            textureType = "exoplanet",
            primaryColorHex = 0xFFEF4444,
            secondaryColorHex = 0xFF38BDF8,
            relativeSizeRatio = 2.2f
        ),
        CelestialBody(
            id = "proxima_b",
            name = "Proxima Centauri b",
            subtitle = "Our Nearest Interstellar Neighbor Planet",
            category = CelestialCategory.EXOPLANETS,
            overview = "Proxima Centauri b is a terrestrial exoplanet orbiting within the habitable zone of Proxima Centauri, the closest star to our Solar System at just 4.24 light-years away. With a mass of roughly 1.07 to 1.17 Earth masses, it is humanity's prime candidate for our first future interstellar robotic flyby mission (such as Breakthrough Starshot).",
            keyFacts = listOf(
                "The closest known exoplanet to Earth, located only 4.24 light-years away.",
                "Orbits in the habitable zone of a red dwarf star every 11.2 Earth days.",
                "Receives about 65% of the solar energy Earth receives from the Sun.",
                "Faces fierce stellar flares from Proxima Centauri, which could challenge the retention of an atmosphere.",
                "Target for laser-propelled nanocraft micro-probes traveling at 20% speed of light."
            ),
            diameter = "Estimated 13,000 km (1.03 × Earth)",
            mass = "1.07 - 1.17 Earth Masses",
            distance = "4.246 Light Years (1.30 pc)",
            orbitalPeriod = "11.186 Earth Days",
            dayLength = "Likely tidally locked (Permanent day / night sides)",
            surfaceGravity = "Estimated 10.0 m/s² (~1.02g)",
            surfaceTemp = "-39°C (Equilibrium temp without greenhouse effect)",
            atmosphere = "Unknown; heavily modeled for oxygen/CO₂ retention against solar flares",
            moonsCount = 0,
            discoveryYear = "2016 by Guillem Anglada-Escudé (ESO Pale Red Dot project)",
            historicalSignificance = "The closest alien world humanity could theoretically reach with interstellar probes within a single human lifetime.",
            nasaMissions = listOf("Hubble Space Telescope", "James Webb Space Telescope (JWST Target)", "Chandra X-Ray"),
            structureLayers = listOf(
                PlanetLayer("Iron-Nickel Core", "0 - 3,200 km", "Metallic core capable of generating magnetic field", 0xFF78716C),
                PlanetLayer("Silicate Mantle", "3,200 - 6,200 km", "Rock mantle with possible convective volcanism", 0xFFB45309),
                PlanetLayer("Surface & Eyeball Ocean", "6,200 - 6,500 km", "Possible liquid ocean pool centered at the sub-stellar point", 0xFF0284C7)
            ),
            textureType = "proxima",
            primaryColorHex = 0xFFF97316,
            secondaryColorHex = 0xFF0EA5E9,
            relativeSizeRatio = 1.05f
        ),

        // === NASA & SPACE EXPLORATION ===
        CelestialBody(
            id = "nasa_agency",
            name = "NASA (National Aeronautics & Space Administration)",
            subtitle = "America's Gateway to the Cosmos (Established 1958)",
            category = CelestialCategory.NASA_MISSIONS,
            overview = "The National Aeronautics and Space Administration is an independent agency of the U.S. federal government responsible for the civil space program, aeronautics research, and space exploration. Established by President Dwight D. Eisenhower in 1958, NASA has led human landings on the Moon, rovers on Mars, telescopes that peer into the dawn of the universe, and robotic missions to every planet in the Solar System.",
            keyFacts = listOf(
                "Created on July 29, 1958 in response to the Soviet Union's launch of Sputnik.",
                "Has sent spacecraft to explore all eight planets, Pluto, numerous asteroids, comets, and interstellar space.",
                "Operates premier space observatories including Hubble, James Webb (JWST), and Chandra.",
                "Successfully landed six crewed missions on the lunar surface during the Apollo Program.",
                "Currently leading the international Artemis coalition to establish sustainable lunar bases and prepare for crewed Mars expeditions."
            ),
            diameter = "Headquarters in Washington, D.C. + 10 Major Centers nationwide",
            mass = "Annual Budget: ~$25 Billion USD / ~18,000 Civil Servants + Thousands of Contractors",
            distance = "Spans Earth to Interstellar Space (Voyager 1 at 24+ Billion km)",
            orbitalPeriod = "N/A",
            dayLength = "24/7 Deep Space Network coverage around the globe",
            surfaceGravity = "Operating across microgravity to extreme gravitational environments",
            surfaceTemp = "Instruments endure from 3K deep space to 1,400°C Parker Solar heat shield",
            atmosphere = "Pioneered life-support systems for human spaceflight",
            moonsCount = 0,
            discoveryYear = "1958",
            historicalSignificance = "Defines the golden age of space exploration, driving groundbreaking technological, medical, and computational advancements for all humanity.",
            nasaMissions = listOf("Mercury", "Gemini", "Apollo", "Space Shuttle", "Voyager", "Hubble", "Curiosity/Perseverance", "JWST", "Artemis"),
            structureLayers = listOf(
                PlanetLayer("Deep Space Network (DSN)", "Goldstone, Madrid, Canberra", "Global antenna network communicating with interplanetary probes", 0xFF38BDF8),
                PlanetLayer("Field Centers (JPL, JSC, KSC, GSFC)", "Across USA", "Specialized design, rocket launch, and astronaut training facilities", 0xFFF59E0B),
                PlanetLayer("Science Mission Directorate", "Earth/Planetary/Astro", "Drives astrophysics, heliophysics, planetary exploration, and Earth science", 0xFF818CF8)
            ),
            textureType = "nasa",
            primaryColorHex = 0xFF2563EB,
            secondaryColorHex = 0xFFDC2626,
            relativeSizeRatio = 1.8f
        ),
        CelestialBody(
            id = "jwst",
            name = "James Webb Space Telescope (JWST)",
            subtitle = "Humanity's Premier Deep Space Infrared Observatory",
            category = CelestialCategory.NASA_MISSIONS,
            overview = "The James Webb Space Telescope is the largest, most powerful optical telescope ever built. Launched on Christmas Day 2021, JWST orbits the Sun at the Second Lagrange Point (L2), 1.5 million kilometers from Earth. Equipped with a 6.5-meter gold-plated beryllium primary mirror and a tennis-court-sized sunshield, Webb observes the cosmos in infrared light, peering back over 13.5 billion years to see the first stars and galaxies formed after the Big Bang.",
            keyFacts = listOf(
                "Primary mirror is 6.5 meters across, composed of 18 hexagonal beryllium segments coated in pure gold.",
                "Protected by a 5-layer tennis-court-sized sunshield maintaining cryogenic operating temperatures below -233°C.",
                "Orbits the Sun at the L2 Lagrange point, 1.5 million km from Earth.",
                "Can detect the thermal heat signature of a bumblebee at the distance of the Moon.",
                "Has discovered the earliest known galaxies (such as JADES-GS-z14-0) shining just 290 million years after the Big Bang."
            ),
            diameter = "Primary Mirror: 6.5 meters / Sunshield: 21.2 m × 14.2 m",
            mass = "6,161 kg (Launch mass)",
            distance = "1.5 Million km from Earth (Sun-Earth L2 Lagrange Point)",
            orbitalPeriod = "Halo orbit around L2 point (~6 months)",
            dayLength = "Continuous 24/7 deep space observations",
            surfaceGravity = "Microgravity (Deep space equilibrium)",
            surfaceTemp = "-233°C (Cold side) / 85°C (Sun-facing side)",
            atmosphere = "High vacuum of deep space",
            moonsCount = 0,
            discoveryYear = "Launched December 25, 2021; First images July 11, 2022",
            historicalSignificance = "Revolutionized observational cosmology, revealing galaxy formation in the cosmic dawn and analyzing exoplanet atmospheres.",
            nasaMissions = listOf("First Deep Field SMACS 0723", "Stephan's Quintet", "Carina Nebula Cosmic Cliffs", "Trappist-1b atmosphere scan"),
            structureLayers = listOf(
                PlanetLayer("Golden Primary Mirror", "6.5m Array", "18 hexagonal beryllium mirrors coated in micro-layer of gold and glass", 0xFFFBBF24),
                PlanetLayer("Scientific Instruments (ISIM)", "Cryogenic Core", "NIRCam, NIRSpec, MIRI, and FGS/NIRISS imaging spectrometers", 0xFF818CF8),
                PlanetLayer("Five-Layer Kapton Sunshield", "Base", "Reflects solar radiation to keep mirrors at -233°C", 0xFFCBD5E1),
                PlanetLayer("Spacecraft Bus & Solar Array", "Hot Side", "Propulsion, reaction wheels, communications, and power generation", 0xFF64748B)
            ),
            textureType = "jwst",
            primaryColorHex = 0xFFFBBF24,
            secondaryColorHex = 0xFF38BDF8,
            relativeSizeRatio = 1.6f
        ),
        CelestialBody(
            id = "artemis_program",
            name = "The Artemis Program",
            subtitle = "Humanity's Return to the Moon & Gateway to Mars",
            category = CelestialCategory.NASA_MISSIONS,
            overview = "The Artemis program is a NASA-led international human spaceflight initiative to return humans to the Moon by the mid-2020s, landing the first woman and first person of color on the lunar surface. Artemis uses the Space Launch System (SLS) mega-rocket, the Orion crew spacecraft, commercial Human Landing Systems (SpaceX Starship HLS / Blue Origin Blue Moon), and the lunar orbital Gateway station to prepare for the next giant leap: crewed missions to Mars.",
            keyFacts = listOf(
                "Goal: Establish a sustainable human permanent base camp at the lunar South Pole.",
                "Powered by the Space Launch System (SLS), generating 8.8 million pounds of thrust (15% more than Saturn V).",
                "Artemis I successfully completed an uncrewed 1.4-million-mile lunar orbit test flight in late 2022.",
                "International partners include ESA (European Space Agency), JAXA (Japan), CSA (Canada), and commercial partners.",
                "Serves as the vital proving ground for technologies required to send human crews to Mars in the 2030s."
            ),
            diameter = "SLS Rocket: 98 meters tall / Orion Spacecraft: 5.0 meters diameter",
            mass = "SLS Launch Mass: 2.6 Million kg (5.75 Million lbs)",
            distance = "Operating between Earth and Lunar Orbit (384,400 km)",
            orbitalPeriod = "Distant Retrograde Orbit (DRO) & Near-Rectilinear Halo Orbit (NRHO)",
            dayLength = "Circadian light regulation for astronaut crew",
            surfaceGravity = "1.62 m/s² (Targeting Lunar South Pole surface)",
            surfaceTemp = "Lunar South Pole craters: -246°C (Coldest places in Solar System)",
            atmosphere = "Orion cabin: 78% N₂ / 21% O₂ at 14.7 psi (Standard Earth atmospheric mix)",
            moonsCount = 0,
            discoveryYear = "Initiated 2017; Artemis I launched Nov 16, 2022",
            historicalSignificance = "Transitions humanity from 'flags and footprints' visits to permanent interplanetary presence and lunar surface economy.",
            nasaMissions = listOf("Artemis I (2022 Flight Test)", "Artemis II (Crewed Lunar Flyby)", "Artemis III (Crewed Lunar Landing)", "Artemis IV (Lunar Gateway Station)"),
            structureLayers = listOf(
                PlanetLayer("Space Launch System (SLS)", "Booster Stage", "Core stage with 4 RS-25 engines + 2 solid rocket boosters", 0xFFEA580C),
                PlanetLayer("Orion Crew Module", "Command Pod", "Deep space habitat with thermal heat shield designed for 40,000 km/h re-entry", 0xFFCBD5E1),
                PlanetLayer("European Service Module (ESM)", "Power/Air/Water", "Solar arrays, propulsion thrusters, water, and oxygen provided by ESA", 0xFF38BDF8),
                PlanetLayer("Human Landing System (HLS)", "Descent/Ascent", "SpaceX Starship HLS modified for deep space lunar touchdown", 0xFF64748B)
            ),
            textureType = "artemis",
            primaryColorHex = 0xFFF97316,
            secondaryColorHex = 0xFF38BDF8,
            relativeSizeRatio = 1.7f
        ),
        CelestialBody(
            id = "voyager_mission",
            name = "Voyager 1 & 2",
            subtitle = "Humanity's Farthest Messengers in Interstellar Space",
            category = CelestialCategory.NASA_MISSIONS,
            overview = "Launched by NASA in 1977, Voyager 1 and Voyager 2 took advantage of a rare planetary alignment that occurs only once every 176 years to explore Jupiter, Saturn, Uranus, and Neptune. In 2012, Voyager 1 became the first human-made object to cross the heliopause and enter interstellar space, now over 24 billion kilometers from Earth.",
            keyFacts = listOf(
                "Voyager 1 is the farthest human-made object from Earth, traveling over 24 billion km (160+ AU) away.",
                "Both spacecraft carry the famous 'Golden Record'—a phonograph record containing sounds, music, and images of Earth for extraterrestrial life.",
                "Voyager 2 is the only spacecraft in history to have visited all four giant outer planets (Jupiter, Saturn, Uranus, Neptune).",
                "Powered by Plutonium Radioisotope Thermoelectric Generators (RTGs) still operating after nearly 50 years.",
                "Captured the famous 'Pale Blue Dot' photo of Earth from 6 billion km away on Carl Sagan's suggestion."
            ),
            diameter = "High-Gain Antenna Dish: 3.7 meters diameter",
            mass = "722 kg (1,592 lbs) each",
            distance = "Voyager 1: 24.3 Billion km (162 AU) / Voyager 2: 20.3 Billion km (136 AU)",
            orbitalPeriod = "Hyperbolic escape trajectory from Solar System (~17 km/s)",
            dayLength = "Round-trip radio signal time to Voyager 1: over 45 hours",
            surfaceGravity = "Microgravity",
            surfaceTemp = "Deep interstellar space: ~3 Kelvin (-270°C)",
            atmosphere = "Interstellar plasma medium outside the Sun's heliosphere bubble",
            moonsCount = 0,
            discoveryYear = "Launched August 20 and September 5, 1977",
            historicalSignificance = "Our first physical emissaries to the stars, bearing the story of human civilization into the cosmic ocean.",
            nasaMissions = listOf("Grand Tour of Solar System", "Interstellar Mission (VIM)", "Pale Blue Dot Portrait (1990)"),
            structureLayers = listOf(
                PlanetLayer("3.7m High-Gain Antenna", "Top", "Directional parabolic dish transmitting signals with a 20-watt radio", 0xFFF1F5F9),
                PlanetLayer("Science Boom Instruments", "Boom Array", "Magnetometer, cosmic ray detectors, plasma wave antennas", 0xFF64748B),
                PlanetLayer("Radioisotope Thermoelectric Generators", "Power Arm", "Plutonium-238 heat source generating electrical power", 0xFFF59E0B),
                PlanetLayer("The Golden Record", "Mount", "Gold-plated copper phonograph record with stylus and playback instructions", 0xFFFBBF24)
            ),
            textureType = "voyager",
            primaryColorHex = 0xFFFBBF24,
            secondaryColorHex = 0xFF64748B,
            relativeSizeRatio = 1.5f
        ),

        // === COSMIC FUNDAMENTALS ===
        CelestialBody(
            id = "big_bang",
            name = "The Big Bang Theory",
            subtitle = "The Genesis of Space, Time, and Energy",
            category = CelestialCategory.COSMIC_CONCEPTS,
            overview = "The Big Bang theory is the prevailing cosmological model explaining the origin and expansion of the observable universe from the earliest known periods through its subsequent large-scale evolution. Approximately 13.8 billion years ago, all matter, energy, space, and time expanded from an unimaginably hot, dense gravitational singularity.",
            keyFacts = listOf(
                "Occurred approximately 13.787 ± 0.020 billion years ago.",
                "Space itself expanded faster than light during the initial fractions of a second (Cosmic Inflation).",
                "The afterglow of this event is visible today in all directions as the Cosmic Microwave Background (CMB) radiation at 2.725 Kelvin.",
                "Created all the initial primordial Hydrogen (~75%), Helium (~25%), and trace Lithium in the universe.",
                "First proposed theoretically by Belgian physicist and Catholic priest Georges Lemaître in 1927."
            ),
            diameter = "Observable Universe: 93 Billion Light Years in diameter",
            mass = "Total Mass-Energy: ~10⁵³ kg (Ordinary Matter ~5%, Dark Matter ~27%, Dark Energy ~68%)",
            distance = "Everywhere around us; origin occurred at all spatial points simultaneously",
            orbitalPeriod = "Age of Universe: 13.8 Billion Years",
            dayLength = "N/A",
            surfaceGravity = "Cosmic gravitational deceleration overcome by Dark Energy acceleration",
            surfaceTemp = "Origin: 10³² Kelvin (Planck temperature) -> Today: 2.725 Kelvin",
            atmosphere = "Universal expansion: Hubble-Lemaître constant ~70 km/s/Mpc",
            moonsCount = 0,
            discoveryYear = "1927 (Lemaître) / 1964 (Penzias & Wilson detected CMB)",
            historicalSignificance = "The definitive scientific foundation of modern cosmology, unifying Einstein's General Relativity with quantum particle physics.",
            nasaMissions = listOf("COBE (Cosmic Background Explorer)", "WMAP (Wilkinson Microwave Anisotropy Probe)", "Planck (ESA/NASA)", "JWST"),
            structureLayers = listOf(
                PlanetLayer("Planck Epoch & Inflation", "t = 0 to 10⁻³² s", "Singularity expands exponentially by factor of 10²⁶", 0xFFFFFBEB),
                PlanetLayer("Nucleosynthesis Era", "t = 3 min to 20 min", "Protons and neutrons fuse to create Hydrogen and Helium atomic nuclei", 0xFFF97316),
                PlanetLayer("Recombination & CMB", "t = 380,000 years", "Electrons bind to nuclei; universe becomes transparent, releasing first light", 0xFFFBBF24),
                PlanetLayer("Cosmic Dawn & Galaxy Era", "t = 100M years to Present", "First stars ignite, assembling into galaxies, solar systems, and life", 0xFF818CF8)
            ),
            textureType = "big_bang",
            primaryColorHex = 0xFFF43F5E,
            secondaryColorHex = 0xFF818CF8,
            relativeSizeRatio = 3.0f
        ),
        CelestialBody(
            id = "stellar_lifecycle",
            name = "Lifecycle of Stars",
            subtitle = "From Molecular Clouds to Supernovae & Black Holes",
            category = CelestialCategory.COSMIC_CONCEPTS,
            overview = "Stars are the cosmic engines and chemical factories of the universe. Born inside collapsing interstellar gas nebulae, stars spend millions to trillions of years fusing lighter elements into heavier elements in their cores. When their nuclear fuel is exhausted, their death creates planetary nebulae, white dwarfs, neutron stars, or black holes, scattering heavy elements like iron, carbon, and gold across the cosmos.",
            keyFacts = listOf(
                "Every atom of carbon, oxygen, calcium, and iron in our bodies was forged inside dying stars (As Carl Sagan said: 'We are made of star-stuff').",
                "Low-mass stars (like our Sun) end their lives gently as glowing planetary nebulae leaving behind white dwarf embers.",
                "Massive stars (over 8 solar masses) explode in catastrophic core-collapse Supernovae, outshining entire galaxies.",
                "The ultra-dense cores left behind become Neutron Stars (Pulsars) or collapse into Black Holes.",
                "Gold, platinum, and uranium are forged primarily in violent collisions between neutron stars (Kilonovae)."
            ),
            diameter = "From Neutron Stars (20 km) to Red Supergiants like Betelgeuse (1 Billion km)",
            mass = "From 0.08 Solar Masses (Red Dwarfs) to 200+ Solar Masses (Hypergiants)",
            distance = "Nearest star: Proxima Centauri (4.24 light-years)",
            orbitalPeriod = "Lifespans range from a few million years (hypergiants) to 10+ trillion years (red dwarfs)",
            dayLength = "Pulsars can rotate hundreds of times per second (e.g. 716 Hz)",
            surfaceGravity = "Neutron star surface: 200 billion times Earth's gravity",
            surfaceTemp = "From 2,500K (cool red giants) to 50,000K (luminous blue hypergiants)",
            atmosphere = "Stellar atmospheres undergo stellar winds, coronal mass ejections, and mass loss",
            moonsCount = 0,
            discoveryYear = "Theoretical astrophysics refined across 20th century (Bethe, Chandrasekhar, Hoyle)",
            historicalSignificance = "Explains cosmic nucleosynthesis: how a universe starting with pure Hydrogen and Helium generated all 118 chemical elements necessary for chemistry and biology.",
            nasaMissions = listOf("Chandra X-Ray Observatory", "Hubble Space Telescope", "NuSTAR", "Fermi Gamma-ray Space Telescope"),
            structureLayers = listOf(
                PlanetLayer("Stellar Nursery Nebula", "Birth", "Gravitational collapse of interstellar cold molecular cloud", 0xFF06B6D4),
                PlanetLayer("Main Sequence Core", "Active Life", "Stable hydrostatic equilibrium fusing Hydrogen to Helium", 0xFFFBBF24),
                PlanetLayer("Red Giant / Supergiant Phase", "Aging", "Helium, Carbon, and Oxygen fusion shells swelling the star outward", 0xFFEA580C),
                PlanetLayer("Supernova Remnant / Core Collapse", "Death", "Cataclysmic explosion leaving behind a White Dwarf, Pulsar, or Black Hole", 0xFF8B5CF6)
            ),
            textureType = "stellar",
            primaryColorHex = 0xFFF59E0B,
            secondaryColorHex = 0xFF8B5CF6,
            relativeSizeRatio = 2.8f
        )
    )

    fun getById(id: String): CelestialBody? = celestialBodies.find { it.id == id }

    fun getByCategory(category: CelestialCategory): List<CelestialBody> =
        celestialBodies.filter { it.category == category }

    val timelineMilestones = listOf(
        TimelineMilestone("1958", "NASA Founded", "President Eisenhower signs the National Aeronautics and Space Act.", "🚀"),
        TimelineMilestone("1961", "First Human in Space", "Yuri Gagarin orbits Earth; Alan Shepard becomes first American in space.", "👨‍🚀"),
        TimelineMilestone("1969", "Apollo 11 Moon Landing", "Neil Armstrong & Buzz Aldrin set foot on the Sea of Tranquility.", "🌕"),
        TimelineMilestone("1977", "Voyager 1 & 2 Launched", "Begins historic Grand Tour of outer planets carrying the Golden Record.", "🛰️"),
        TimelineMilestone("1990", "Hubble Deployed", "Space Shuttle Discovery launches Hubble Space Telescope into orbit.", "🔭"),
        TimelineMilestone("1998", "ISS Construction", "First module (Zarya) launched, establishing continuous human space habitation.", "🛰️"),
        TimelineMilestone("2012", "Curiosity Lands on Mars", "Sky crane delivers 1-ton rover to explore ancient Martian habitability.", "🔴"),
        TimelineMilestone("2015", "Pluto Flyby", "New Horizons captures first close-up high-resolution images of Pluto's heart.", "❤️"),
        TimelineMilestone("2019", "First Black Hole Imaged", "Event Horizon Telescope reveals silhouette of M87* supermassive black hole.", "🕳️"),
        TimelineMilestone("2021", "JWST Launched", "James Webb Space Telescope launches on Christmas Day to peer at cosmic dawn.", "✨"),
        TimelineMilestone("2022", "Artemis I Success", "Uncrewed Orion spacecraft completes 25-day lunar test flight.", "🌙"),
        TimelineMilestone("2024+", "Europa Clipper & Artemis II", "Journey to ocean worlds and crewed lunar missions around the Moon.", "🌌")
    )
}

data class TimelineMilestone(
    val year: String,
    val title: String,
    val description: String,
    val icon: String
)
